"""The blueprint compiler.

A lesson teaches and a blueprint specifies. The blueprint is what you read when you are
implementing something and need to know exactly what GCC does, so it has no narrative, no
analogies, and no dependency on any lesson. Nine sections, always all nine, because an
absent section is itself a claim and a heading with `TODO` under it is an honest one.

Some of those sections should never be typed by a person. GCC keeps the parts that have to
stay consistent across fifty one targets and twelve front ends in machine readable form:
`gimple.def` is the complete list of GIMPLE statement codes, `rtl.def` is the complete list
of RTX codes with a format string describing every operand slot, `target.def` is every
target hook with its documentation inline. Transcribing those into prose gets them wrong
immediately and keeps them wrong forever. So `bpc` generates them and fails the build when
what is in the file is not what the generator would produce today.

    bpc build       regenerate every generated section from the pinned tree
    bpc check       fail if any generated section is stale
    bpc coverage    the coverage ledger, and fail on anything unclassified
    bpc status      the per blueprint status table

A generated block is fenced by markers, and everything between them belongs to `bpc`:

    <!-- bpc:begin gimple-codes -->
    ...
    <!-- bpc:end gimple-codes -->

Generated sections carry no `path:line@tag` citations, and that is deliberate. `refcheck`
proves that a hand written claim still points at the code it was written from, by hashing a
few lines around it. For generated content `bpc check` proves something stronger: not that
the source looks similar, but that regenerating from the source produces this exact text.
Two checks on the same content would only mean two things to update. So generated blocks
reference GCC by file and line without a tag, the tag is declared once in the blueprint
header, and `refcheck` leaves them alone.
"""

from __future__ import annotations

import re
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
GCC_ROOT = REPO_ROOT / "vendor" / "gcc" / "gcc"
BLUEPRINTS = REPO_ROOT / "blueprints"
PINNED_TAG = "releases/gcc-16.2.0"

BEGIN = re.compile(r"^(?P<indent>\s*)<!--\s*bpc:begin\s+(?P<id>[\w.-]+)\s*-->\s*$")
END = re.compile(r"^\s*<!--\s*bpc:end\s+(?P<id>[\w.-]+)\s*-->\s*$")

WARNING = (
    "*Generated by `bpc build` from the pinned GCC tree. Do not edit inside the markers, "
    "edit the generator.*"
)


class BpcError(RuntimeError):
    """Something a blueprint author needs to fix, phrased so they can fix it."""


@dataclass
class Block:
    """One generated region of a blueprint."""

    id: str
    path: Path
    start: int
    end: int
    body: str


@dataclass
class Blueprint:
    """One blueprint file, with its header fields and its generated blocks."""

    path: Path
    text: str

    @property
    def id(self) -> str:
        return self.path.stem

    @property
    def title(self) -> str:
        for line in self.text.splitlines():
            if line.startswith("# "):
                return line[2:].strip()
        raise BpcError(f"{self.path} has no title")

    def header(self, name: str) -> str:
        """A value from the header block, for example `Status` or `Applies to`."""
        m = re.search(rf"^\*\*{re.escape(name)}:\*\*\s*(?P<value>.+)$", self.text, re.MULTILINE)
        return m.group("value").strip() if m else ""

    @property
    def sections(self) -> list[str]:
        return re.findall(r"^##\s+(\d+\..*)$", self.text, re.MULTILINE)

    @property
    def blocks(self) -> list[Block]:
        lines = self.text.splitlines()
        blocks: list[Block] = []
        open_at: tuple[str, int] | None = None
        for n, line in enumerate(lines):
            if (m := BEGIN.match(line)) is not None:
                if open_at is not None:
                    raise BpcError(f"{self.path}:{n + 1}: a bpc block opens inside another one")
                open_at = (m.group("id"), n)
            elif (m := END.match(line)) is not None:
                if open_at is None:
                    raise BpcError(f"{self.path}:{n + 1}: bpc:end with no bpc:begin")
                if m.group("id") != open_at[0]:
                    raise BpcError(
                        f"{self.path}:{n + 1}: bpc:end {m.group('id')} closes "
                        f"bpc:begin {open_at[0]}"
                    )
                blocks.append(
                    Block(
                        id=open_at[0],
                        path=self.path,
                        start=open_at[1],
                        end=n,
                        body="\n".join(lines[open_at[1] + 1 : n]).strip("\n"),
                    )
                )
                open_at = None
        if open_at is not None:
            raise BpcError(f"{self.path}:{open_at[1] + 1}: bpc:begin {open_at[0]} is never closed")
        return blocks


Generator = Callable[[Path], str]
GENERATORS: dict[str, Generator] = {}


def generator(name: str) -> Callable[[Generator], Generator]:
    def register(fn: Generator) -> Generator:
        GENERATORS[name] = fn
        return fn

    return register


def load(directory: Path | None = None) -> list[Blueprint]:
    """Every blueprint in the repository, in file order. The template is not one."""
    directory = directory or BLUEPRINTS
    return [
        Blueprint(path=p, text=p.read_text(encoding="utf-8"))
        for p in sorted(directory.glob("BP-*.md"))
    ]


def render(block_id: str, root: Path) -> str:
    """What a generated block should contain today."""
    _register_generators()
    if block_id not in GENERATORS:
        known = ", ".join(sorted(GENERATORS)) or "none"
        raise BpcError(f"no generator called {block_id!r}. Registered generators: {known}")
    body = GENERATORS[block_id](root).strip("\n")
    return f"{WARNING}\n\n{body}"


def rewrite(bp: Blueprint, root: Path) -> str:
    """The blueprint with every generated block replaced by what it should contain."""
    lines = bp.text.splitlines()
    out: list[str] = []
    at = 0
    for block in bp.blocks:
        out += lines[at : block.start + 1]
        out += render(block.id, root).splitlines()
        at = block.end
    out += lines[at:]
    return "\n".join(out) + ("\n" if bp.text.endswith("\n") else "")


def build(directory: Path | None = None, root: Path | None = None) -> list[Path]:
    """Regenerate every generated block. Returns the files that actually changed."""
    root = root or GCC_ROOT
    changed = []
    for bp in load(directory):
        new = rewrite(bp, root)
        if new != bp.text:
            bp.path.write_text(new, encoding="utf-8")
            changed.append(bp.path)
    return changed


def check(directory: Path | None = None, root: Path | None = None) -> list[str]:
    """Every reason the blueprints would fail a build."""
    root = root or GCC_ROOT
    problems: list[str] = []
    for bp in load(directory):
        try:
            problems += _check_shape(bp)
            for block in bp.blocks:
                want = render(block.id, root)
                if block.body != want:
                    problems.append(
                        f"{bp.path}:{block.start + 1}: the {block.id} block is stale. "
                        f"{_first_difference(block.body, want)} Run `just blueprints`."
                    )
        except BpcError as exc:
            problems.append(str(exc))
    return problems


REQUIRED_SECTIONS = [
    "1. Purpose and scope",
    "2. Data structures",
    "3. Algorithms",
    "4. Invariants",
    "5. Observable behaviour",
    "6. Edge cases and error paths",
    "7. Interactions",
    "8. Conformance",
    "9. Port notes",
]
STATUSES = ("stub", "partial", "complete")


def _check_shape(bp: Blueprint) -> list[str]:
    """All nine headings, a legal status, and a header that names the pinned tag."""
    problems = []
    have = [s.split(".", 1)[0] for s in bp.sections]
    for n, want in enumerate(REQUIRED_SECTIONS, start=1):
        if str(n) not in have:
            problems.append(f"{bp.path}: section {want!r} is missing. All nine are required.")
    status = bp.header("Status")
    if status not in STATUSES:
        problems.append(f"{bp.path}: status is {status!r}, which is not one of {STATUSES}.")
    if PINNED_TAG not in bp.header("Applies to"):
        problems.append(f"{bp.path}: the header does not say it applies to {PINNED_TAG}.")
    return problems


def _register_generators() -> None:
    """Import every generator module so that its blocks are known.

    This is at the bottom rather than the top because a generator module imports
    `generator` from here, and the decorator has to exist before the module runs.
    """
    from tools.bpc import gimple  # noqa: F401


def _first_difference(have: str, want: str) -> str:
    """The first line that differs, because a stale block diff is otherwise unreadable."""
    a, b = have.splitlines(), want.splitlines()
    for n, (x, y) in enumerate(zip(a, b, strict=False), start=1):
        if x != y:
            return f"Line {n} of the block reads {x.strip()[:60]!r}, expected {y.strip()[:60]!r}."
    if len(a) != len(b):
        return f"The block has {len(a)} lines and should have {len(b)}."
    return "It differs in trailing whitespace."
