"""The blueprint pages of the published book, generated from the blueprints themselves.

A blueprint is a document, not a lesson, and it belongs on the site next to the lessons that
cite it. Two things stop that from being one line of MkDocs configuration.

The documents live in `blueprints/` at the root of the repository, because that is where a
reader on GitHub looks for them and where the lessons link. Copying them under `docs/` would
mean two of each, and the day they differ the reader has no way to know which one is real.
So each page is a one line snippet include of the document, the way the glossary page is,
and there is one copy of every blueprint.

The index is the other thing. Nine documents with a status apiece, one complete and eight
below it, is exactly the sort of table that goes stale the week after somebody writes it by
hand. It is generated from the headers, so a blueprint that exists is on the page and a
blueprint that does not is not, and `bpc pages --check` fails the build when the committed
page has drifted from the documents.
"""

from __future__ import annotations

import re
from pathlib import Path

from tools.bpc import BLUEPRINTS, REPO_ROOT, Blueprint, load

DOCS = REPO_ROOT / "docs"
PAGES = DOCS / "blueprints"
INDEX = DOCS / "blueprints.md"
MKDOCS = REPO_ROOT / "site" / "mkdocs.yml"

#: The documents that are not blueprints and get a page of their own anyway. `NOTATION` is
#: the pseudocode dialect every algorithm in every blueprint is written in, and a reader who
#: hits an algorithm before finding it will read it as broken C.
COMPANIONS = ("NOTATION",)

HEADER = """# The blueprints

A blueprint is a specification and not a lesson. It says what GCC does precisely enough to implement against, with every claim carrying a citation into the pinned tree, and it does not try to teach. The lessons are the way in. These are what you write code against once you are in.

Every one is checked on every push. The citations resolve against `releases/gcc-16.2.0`, and the sections marked as generated are rebuilt from GCC's own `.def` files rather than typed, so a document cannot quietly fall behind the compiler it describes.

Three statuses. A **stub** has all nine sections and says in its header what it does not cover yet, because a lesson needs somewhere to point today and a title with a promise under it is not somewhere. A **partial** has its generated sections landed and prose still to write. A **complete** one is finished.

The pseudocode every algorithm is written in is [NOTATION](blueprints/NOTATION.md), and it is worth five minutes before you reach the first algorithm, because it is not C and reading it as C will mislead you in two places.

"""

FOOTER = """
This page is generated by `python -m tools.bpc pages`. Edit the blueprints rather than editing here.
"""

INCLUDE = """<!-- {name} lives in blueprints/{name}.md at the root of the repository, because that is where a reader on GitHub looks for it and where the lessons link. This page pulls in the same file, so there is one copy and not two. Generated by `python -m tools.bpc pages`. -->

--8<-- "blueprints/{name}.md"
"""


def summary(bp: Blueprint) -> str:
    """The first paragraph under the title, which is what the document says it is for."""
    body = bp.text.split("**Last verified:**", 1)[-1]
    for para in body.split("\n\n")[1:]:
        line = para.strip()
        if line and not line.startswith(("#", "**", "|", "<!--")):
            return " ".join(line.split())
    return ""


def row(bp: Blueprint) -> str:
    generated = bp.header("Generated sections")
    sections = "none" if generated == "none" else f"{generated} of 9"
    return (
        f"| [{bp.id}](blueprints/{bp.id}.md) | {bp.title.split(', ', 1)[-1]} | "
        f"{bp.header('Status')} | {sections} | {bp.header('Target-dependent')} |"
    )


def index_page(found: list[Blueprint]) -> str:
    counts: dict[str, int] = {}
    for bp in found:
        counts[bp.header("Status")] = counts.get(bp.header("Status"), 0) + 1
    said = ", ".join(f"{n} {k}" for k, n in sorted(counts.items()))

    out = [
        HEADER,
        "| | What it specifies | Status | Generated sections | Target dependent |\n",
        "|---|---|---|---|---|\n",
    ]
    out.extend(f"{row(bp)}\n" for bp in found)
    out.append(f"\n{len(found)} of 58 written: {said}.\n")
    out.append("\n## What each one is for\n")
    for bp in found:
        out.append(f"\n### [{bp.id}]({'blueprints/' + bp.id}.md), {bp.title.split(', ', 1)[-1]}\n")
        out.append(f"\n{summary(bp)}\n")
    out.append(FOOTER)
    return "".join(out)


def wanted(found: list[Blueprint]) -> dict[Path, str]:
    """Every page this generator owns, and what should be in it."""
    pages = {INDEX: index_page(found)}
    for name in [bp.id for bp in found] + list(COMPANIONS):
        pages[PAGES / f"{name}.md"] = INCLUDE.format(name=name)
    return pages


def nav_problems(found: list[Blueprint], config: Path | None = None) -> list[str]:
    """Every blueprint has to be in the site navigation, or it is published and unreachable.

    MkDocs is happy to build a page nothing links to, and `--strict` does not mind either,
    so a blueprint added without a nav entry ships as a URL only its author knows.
    """
    text = Path(config or MKDOCS).read_text(encoding="utf-8")
    return [
        f"{name} has a page and no entry in {Path(config or MKDOCS).name}"
        for name in [bp.id for bp in found] + list(COMPANIONS)
        if not re.search(rf"blueprints/{re.escape(name)}\.md\s*$", text, re.MULTILINE)
    ]


def build(directory: Path | None = None) -> list[Path]:
    found = load(directory or BLUEPRINTS)
    written = []
    for path, text in wanted(found).items():
        path.parent.mkdir(parents=True, exist_ok=True)
        if not path.exists() or path.read_text(encoding="utf-8") != text:
            path.write_text(text, encoding="utf-8")
            written.append(path)
    return written


def check(directory: Path | None = None, config: Path | None = None) -> list[str]:
    found = load(directory or BLUEPRINTS)
    problems = []
    for path, text in wanted(found).items():
        rel = path.relative_to(REPO_ROOT)
        if not path.exists():
            problems.append(f"{rel} is missing, run `just blueprint-pages`")
        elif path.read_text(encoding="utf-8") != text:
            problems.append(f"{rel} is out of date, run `just blueprint-pages`")
    for path in sorted(PAGES.glob("*.md")) if PAGES.exists() else []:
        if path not in wanted(found):
            problems.append(f"{path.relative_to(REPO_ROOT)} has no blueprint behind it")
    return problems + nav_problems(found, config)
