"""Recorded dumps, so Tier 0 keeps working when the network does not.

Every entry is one compilation: the source, the flags, the compiler that produced it, the
target it produced it for, and the dumps. Entries are generated by `just corpus` against
the pinned compiler and committed, because the point of them is to be the same every time.

An entry records which compiler made it, and the banner shows that to the reader. An
observation in this book is only true of a version and a target, and a reader looking at a
recorded dump has to be able to see which.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from datetime import date
from pathlib import Path

CORPUS_ROOT = Path(__file__).resolve().parent.parent / "corpora" / "dumps"


@dataclass
class Record:
    """One recorded compilation."""

    entry: str
    source: str
    args: list[str]
    compiler: str
    target: str
    recorded: str
    dump_texts: dict[str, str] = field(default_factory=dict)
    asm: str = ""

    def to_json(self) -> dict:
        return {
            "entry": self.entry,
            "source": self.source,
            "args": self.args,
            "compiler": self.compiler,
            "target": self.target,
            "recorded": self.recorded,
            "asm": self.asm,
            "dumps": self.dump_texts,
        }

    @classmethod
    def from_json(cls, data: dict) -> Record:
        return cls(
            entry=data["entry"],
            source=data["source"],
            args=list(data["args"]),
            compiler=data["compiler"],
            target=data["target"],
            recorded=data["recorded"],
            dump_texts=dict(data["dumps"]),
            asm=data.get("asm", ""),
        )

    def __str__(self) -> str:
        return f"{self.entry}: {len(self.dump_texts)} dump(s) from {self.compiler}"


def path_for(entry: str, root: Path | str | None = None) -> Path:
    return Path(root or CORPUS_ROOT) / f"{entry}.json"


def save(record: Record, root: Path | str | None = None) -> Path:
    p = path_for(record.entry, root)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(record.to_json(), indent=1, sort_keys=True) + "\n", encoding="utf-8")
    return p


def load(entry: str, root: Path | str | None = None) -> Record:
    p = path_for(entry, root)
    if not p.exists():
        available = ", ".join(sorted(x.stem for x in p.parent.glob("*.json"))) or "none"
        raise FileNotFoundError(f"no corpus entry {entry!r}. Recorded entries: {available}")
    return Record.from_json(json.loads(p.read_text(encoding="utf-8")))


def entries(root: Path | str | None = None) -> list[str]:
    d = Path(root or CORPUS_ROOT)
    return sorted(p.stem for p in d.glob("*.json")) if d.exists() else []


def record(backend, entry: str, source: str, *args: str, dumps: list[str]) -> Record:
    """Run a compilation on a local backend and keep the result."""
    result = backend.compile(source, *args, dumps=dumps)
    if not result.ok:
        raise RuntimeError(f"cannot record {entry!r}, the compile failed:\n{result.stderr}")
    return Record(
        entry=entry,
        source=source,
        args=list(args),
        compiler=backend.version(),
        target=backend.target(),
        recorded=date.today().isoformat(),
        dump_texts=dict(result.dump_texts),
        asm=result.asm,
    )
